# config.py
import os

ZHIPU_API_KEY = os.environ.get("ZHIPU_API_KEY", "你的真实API-KEY")
ZHIPU_MODEL_NAME = "glm-4.7-flash"

SPEAK_THRESHOLD = 0.6
MIN_MEANING_SCORE = 4
MAX_RETRIES = 3
CURIOSITY_THRESHOLD = 3

SHORT_TO_LONG_COUNT = 5
LONG_TO_PERMANENT_COUNT = 7

VISION_MODE = "keyboard"
SCENE_DESCRIPTION = "一只橘猫趴在窗台上，阳光照在它身上"
IMAGE_PATH = None

USE_CLOUD_CLASSIFIER = False  # 默认关闭云端分类器，省钱

EMOTION_DECAY_RATE = 0.05
EMOTION_SPEAK_ENERGY_COST = 0.03
EMOTION_SILENCE_ENERGY_GAIN = 0.05
EMOTION_LEARN_CURIOSITY_GAIN = 0.1
EMOTION_LEARN_PLEASURE_GAIN = 0.05
EMOTION_UNKNOWN_CURIOSITY_GAIN = 0.15
EMOTION_QUESTION_CURIOSITY_COST = 0.2

REJECTION_BONUS_MAX = 0.3
REJECTION_BONUS_PER_STREAK = 0.1
REJECTION_LENIENT_THRESHOLD = 3

MEMORY_INFLUENCE_PROB = 0.4
WORD_INSERT_PROB = 0.3
MOSAIC_PROB = 0.5
HINT_USE_PROB = 0.7